config/routes.rb
Rails.application.routes.draw do

  root to: 'fizz_buzz#index', as: :home

  get '/show/:page/:per_page', to: 'fizz_buzz#index', as: :show

  match '/like', to: 'fizz_buzz#like', as: :set_like, via: :post

end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id             :integer          not null, primary key
#  number_to_like :integer          not null
#  like_it        :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Like < ActiveRecord::Base

  validates :number_to_like, :like_it, numericality: :only_integer

  # Saves number and like
  #
  # if number is new record it creates it and set like_it to 1
  # if number is already in DB it sets like_it to 0
  def self.like_toggle(number)
    like = self.find_by_number_to_like number
    if like
      case like.like_it
        when 0
          like.like_it = 1
          like.save!
          return true
        when 1
          like.like_it = 0
          like.save!
          return false
      end
    else
      self.create!(number_to_like: number, like_it: 1)
      return true
    end
  end

  def self.get_likes(from, to)
    self.where(number_to_like: from..to).to_a
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fizz_buzz_controller.rb
class FizzBuzzController < ApplicationController


  # @facade should be Object itself which would handle
  # all logic of handling pagination to not pollute controller method
  # ideally place in Facades/fizz_buzz_facade.rb
  # and called in index method @facade = FizzBuzz.new(fizz_buzz_values, listing_params, MAX_ITEMS)
  def index
    @facade                    = fizz_buzz_index_facade.to_h
    @facade[:pages]            = fizz_buzz_index_facade.pages
    @facade[:per_page_options] = PER_PAGE_OPTIONS.map { |val| [val, val] }

    from = @facade[:values][0][:number]
    to = @facade[:values][-1][:number]
    @facade[:likes] = Like.get_likes(from, to)

    respond_to do |format|
      format.html
      format.json { render json: @facade[:values] }
    end

  end

  # Calls Like model to toggle like
  # Like model should have validation not allowing to save 0
  # and use save! to produce Exception to work it properly
  #
  # This might create record with 0 number and marked number as liked
  def like
    begin
      liked = Like.like_toggle(params[:number_to_like])
      render json: {res: true, liked: liked}
    rescue
      render json: {res: false}
    end
  end

  def listing_params
    {
        page:     params[:page].nil? ? DEF_PAGE_NUM : params[:page].to_i ,
        per_page: params[:per_page].nil? ? DEF_PER_PAGE_NUM : params[:per_page].to_i
    }
  end

  def fizz_buzz_index_facade
    index_view = Struct.new(:values, :page, :per_page, :max_items) do

      def pages
        (self.max_items / self.per_page).to_i
      end

    end

    index_view.new(fizz_buzz_values, *listing_params.values, MAX_ITEMS)
  end

  def fizz_buzz_values
     MyFizzBuzz.new(listing_params).fizz_buzz_page
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fizz_buzz_helper.rb
module FizzBuzzHelper
end

app/views/fizz_buzz/index.html.haml
.row
  .big-6
    %h1 FizzBuzz
    -#=form_tag(show_path(page: @facade[:page], per_page: @facade[:per_page] ), method: :get, id: 'pagination-form') do
    -#  =label_tag(:per_page, 'Select page Items', class: 'per-page-select-label')
    -#  =select_tag(:per_page, options_for_select(@facade[:per_page_options], @facade[:per_page]), class: 'per-page-select')
    -#  =hidden_field_tag(:page, @facade[:page])

    =render partial: 'partials/pagination', locals: @facade

    %ul.fizz-buzz-list.clearfix
      -@facade[:values].each do |val|
        -fizz_buzz_class = (val[:fizz_buzz].is_a? String) ? val[:fizz_buzz].downcase : nil
        -link = capture_haml do
          = link_to val[:fizz_buzz], set_like_path(number_to_like: val[:number]), method: :post, remote: true, class: "set-like #{fizz_buzz_class}"
        -liked = false
        -@facade[:likes].each do |like|
          -if val[:number] == like.number_to_like && like.like_it == 1
            %li.item.liked= link
            -liked = true
            -break
        -unless liked
          %li.item= link

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/partials/_pagination.html.haml
%ul.pagination{"aria-label" => "Pagination", :role => "navigation"}
  -if page > 1
    %li.pagination-previous
      %a{href: '#', data: {page: page - 1}} Prev
  -else
    %li.inactive Prev
  -skip = false
  -pages.times do |page_index|
    -page_index += 1
    -if page_index > 4 && page_index < pages - 4
      -unless skip
        %li.ellipsis{"aria-hidden" => "true"}
      -skip = true
      -next

    -elsif page == page_index
      %li.current=page_index
    -else
      %li
        %a{href: show_path(page: page_index, per_page: @facade[:per_page] ), data: {page: page_index}}= page_index
  -if page < pages
    %li.pagination-next
      %a{href: '#', data: {page: page + 1}} Next
  -else
    %li.inactive Next